#CI: WITH EVRY PR AND PUSH IT TRIGGRS AUTOMATED BUILD + TEST, CATCING INTEGRATION BUGS EARLY
#CD(CONTINOIUS DELIVERY) AUTOMATED PACKAGING/STAGING SO RELEASE IS ALWAYS ONE CLICK AWAY 
#CONTINOUS DEPLOYMENT : DELIVERY + AUTOMATIC PRODUCTION RELEASE 


#WORKFLOW MEANS A YAML FILE DESCRIBING THE AUTOMATION
#EVENT(ON): WHAT TRIGGERS THE WORKFLOW PUSH PULL SCHEDULE ECT.
#JOB:SET OF STEPS THAT RUN ON THE SAME RUNNER 
#STEP: A SINGLE TASK A SHELL COMMAND OR AN ACTION 
# ACTION : A REUSABLE UNIT OF CODE 
#RUNNER : THE VM/CONTAINER THAT EXECUTES THE JOB

#STRUCTURE OF A SIMPLE WORKFLOW 
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v4
      - run: echo "hello CI"
 
